import 'package:roadside_help/domain/entities/helper.dart';

final List<Helper> demoHelpers = [
  Helper(
    id: 'demo-puncture-1',
    name: 'QuickFix Tyres',
    type: HelperType.PUNCTURE_SHOP,
    latitude: 12.9735,
    longitude: 77.5971,
    phoneNumber: '+919876543210',
    smsCapable: true,
    openingHours: 'Open now',
    source: HelperSource.CURATED,
    lastUpdated: DateTime.utc(2026, 6, 9, 8, 30),
  ),
  Helper(
    id: 'demo-puncture-2',
    name: 'Metro Wheel Care',
    type: HelperType.PUNCTURE_SHOP,
    latitude: 12.9677,
    longitude: 77.5911,
    phoneNumber: '+919876543211',
    smsCapable: true,
    openingHours: 'Open until 10 PM',
    source: HelperSource.CURATED,
    lastUpdated: DateTime.utc(2026, 6, 9, 8, 15),
  ),
  Helper(
    id: 'demo-fuel-1',
    name: 'Oasis Fuel Point',
    type: HelperType.PETROL_PUMP,
    latitude: 12.9752,
    longitude: 77.5888,
    phoneNumber: '+919876543212',
    smsCapable: false,
    openingHours: '24 hours',
    source: HelperSource.CURATED,
    lastUpdated: DateTime.utc(2026, 6, 9, 8, 10),
  ),
  Helper(
    id: 'demo-fuel-2',
    name: 'GreenLine Petrol',
    type: HelperType.PETROL_PUMP,
    latitude: 12.9659,
    longitude: 77.6022,
    phoneNumber: '+919876543213',
    smsCapable: false,
    openingHours: '24 hours',
    source: HelperSource.THIRD_PARTY,
    lastUpdated: DateTime.utc(2026, 6, 9, 7, 55),
  ),
  Helper(
    id: 'demo-mechanic-1',
    name: 'RoadPro Mechanics',
    type: HelperType.MECHANIC,
    latitude: 12.9789,
    longitude: 77.6014,
    phoneNumber: '+919876543214',
    smsCapable: true,
    openingHours: 'Open now',
    source: HelperSource.CURATED,
    lastUpdated: DateTime.utc(2026, 6, 9, 8, 5),
  ),
  Helper(
    id: 'demo-mechanic-2',
    name: 'FastStart Garage',
    type: HelperType.MECHANIC,
    latitude: 12.9633,
    longitude: 77.5874,
    phoneNumber: '+919876543215',
    smsCapable: true,
    openingHours: 'Open until 9 PM',
    source: HelperSource.THIRD_PARTY,
    lastUpdated: DateTime.utc(2026, 6, 9, 7, 45),
  ),
];

List<Helper> demoHelpersForType(HelperType type) {
  return demoHelpers.where((helper) => helper.type == type).toList();
}
